<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Heading' => 'Título',
    'About' => 'Sobre',
    'Contact' => 'Contato',
    'Login' => 'Login',
    'Congratulations!' => 'Parabéns!',
    'You have successfully created your Yii-powered application.' => 'Você criou com sucesso sua aplicação Yii.',
    'Get started with Yii' => 'Primeiros passos',
    'Yii Documentation' => 'Documentação',
    'Yii Forum' => 'Fórum',
    'Yii Extensions' => 'Extensões',
];
