<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'A propos',
    'Contact' => 'Contact',
    'Login' => 'Connexion',
    'Congratulations!' => 'Félicitations !',
    'You have successfully created your Yii-powered application.' => 'Vous avez créé votre application Yii avec succès.',
    'Get started with Yii' => 'Débuter avec Yii',
    'Yii Documentation' => 'Documentation Yii',
    'Yii Forum' => 'Forum Yii',
    'Yii Extensions' => 'Extensions Yii',
];
